version: '3'
services:
  el6:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-el6
    volumes:
      - .:/home/builduser/configsnap

  el7:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-el7
    volumes:
      - .:/home/builduser/configsnap

  fedora:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-fedora
    volumes:
      - .:/home/builduser/configsnap

  deb:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-deb
    volumes:
      - .:/home/builduser/configsnap
